In [625]:
import pandas as pd
import numpy as np

hr_dataset = pd.read_csv("D:/My files/Deep learning/Jupyter notebooks/HR dataset/HRDataset_v13.csv")

In [626]:
hr_dataset.shape

(310, 35)

In [627]:
def drop_duplicate_records(dataset_org):
    duplicate_records = dataset_org.duplicated()
    print("Duplicate records count:",sum(duplicate_records))
    hr_dataset_unique = dataset_org.drop_duplicates()
    print("After dropping duplicates:",hr_dataset_unique.shape)
    return hr_dataset_unique

In [628]:
hr_dataset = drop_duplicate_records(hr_dataset)
hr_dataset.shape


Duplicate records count: 0
After dropping duplicates: (310, 35)


(310, 35)

In [629]:
hr_dataset.describe

<bound method NDFrame.describe of                 Employee_Name       EmpID  MarriedID  MaritalStatusID  \
0                  Brown, Mia  1103024456          1                1   
1             Howard, Estelle  1211050782          1                1   
2                 Singh, Nan   1307059817          0                0   
3            Smith, Leigh Ann   711007713          1                1   
4            Bunbury, Jessica  1504073368          1                1   
..                        ...         ...        ...              ...   
305  Ait Sidi, Karthikeyan     1307060199          1                1   
306           Favis, Donald    1412071562          0                0   
307            Lajiri,  Jyoti  1108028108          1                1   
308    Semizoglou, Jeremiah     904013591          1                1   
309                South, Joe  1308060959          0                0   

     GenderID  EmpStatusID  DeptID  PerfScoreID  FromDiversityJobFairID  \
0           0 

In [630]:
def find_column_duplicates(dataset_org, column):
    return dataset_org.duplicated(column, keep = False)

In [631]:
empid_duplicates = find_column_duplicates(hr_dataset, 'EmpID')
empid_duplicates.sum()

0

In [632]:
def drop_columns(data_set, columns):
    return data_set.drop(columns, axis = 1, inplace = True) 
    

In [633]:
hr_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 310 entries, 0 to 309
Data columns (total 35 columns):
Employee_Name                 310 non-null object
EmpID                         310 non-null int64
MarriedID                     310 non-null int64
MaritalStatusID               310 non-null int64
GenderID                      310 non-null int64
EmpStatusID                   310 non-null int64
DeptID                        310 non-null int64
PerfScoreID                   310 non-null int64
FromDiversityJobFairID        310 non-null int64
PayRate                       310 non-null float64
Termd                         310 non-null int64
PositionID                    310 non-null int64
Position                      310 non-null object
State                         310 non-null object
Zip                           310 non-null int64
DOB                           310 non-null object
Sex                           310 non-null object
MaritalDesc                   310 non-null object
Citiz

In [634]:
columns = ['Employee_Name','Sex','Zip','FromDiversityJobFairID','Position','MaritalDesc','TermReason','EmploymentStatus','Department','ManagerName','PerformanceScore','DaysLateLast30']
drop_columns(hr_dataset, columns) 

In [636]:
hr_dataset['DOB']

0      24-11-1987
1      16-09-1985
2      19-05-1988
3      14-06-1987
4      01-06-1964
          ...    
305    05-05-1975
306    30-07-1964
307    23-04-1986
308    09-02-1983
309    09-09-1965
Name: DOB, Length: 310, dtype: object

In [637]:
import datetime
from datetime import date

def calculate_year(column, dateFormat):
    today = date.today()
    difference = today.year - hr_dataset[column].apply(lambda x: datetime.datetime.strptime(x,dateFormat).date().year)
    return difference

In [638]:
hr_dataset['Age'] = calculate_year('DOB', "%d-%m-%Y")

In [639]:
hr_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 310 entries, 0 to 309
Data columns (total 24 columns):
EmpID                         310 non-null int64
MarriedID                     310 non-null int64
MaritalStatusID               310 non-null int64
GenderID                      310 non-null int64
EmpStatusID                   310 non-null int64
DeptID                        310 non-null int64
PerfScoreID                   310 non-null int64
PayRate                       310 non-null float64
Termd                         310 non-null int64
PositionID                    310 non-null int64
State                         310 non-null object
DOB                           310 non-null object
CitizenDesc                   310 non-null object
HispanicLatino                310 non-null object
RaceDesc                      310 non-null object
DateofHire                    310 non-null object
DateofTermination             103 non-null object
ManagerID                     302 non-null float64
Re

In [642]:
hr_dataset['Age']

0      33
1      35
2      32
3      33
4      56
       ..
305    45
306    56
307    34
308    37
309    55
Name: Age, Length: 310, dtype: int64

In [643]:
hr_dataset['DOB']

0      24-11-1987
1      16-09-1985
2      19-05-1988
3      14-06-1987
4      01-06-1964
          ...    
305    05-05-1975
306    30-07-1964
307    23-04-1986
308    09-02-1983
309    09-09-1965
Name: DOB, Length: 310, dtype: object

In [602]:
hr_dataset["RecruitmentSource"].unique()

array(['Diversity Job Fair', 'Pay Per Click - Google',
       'Website Banner Ads', 'Social Networks - Facebook Twitter etc',
       'Billboard', 'Monster.com', 'Professional Society', 'Other',
       'Indeed', 'Employee Referral', 'Search Engine - Google Bing Yahoo',
       'Glassdoor', 'MBTA ads', 'Vendor Referral', 'Information Session',
       'Internet Search', 'Newspager/Magazine', 'On-campus Recruiting',
       'Word of Mouth', 'Pay Per Click', 'On-line Web application',
       'Careerbuilder', 'Company Intranet - Partner'], dtype=object)

In [603]:
hr_dataset['YearsOfExperience'] = calculate_year('DateofHire', "%m-%d-%Y")

In [604]:
hr_dataset

EmpID  MarriedID  MaritalStatusID  GenderID  EmpStatusID  DeptID  \
0    1103024456          1                1         0            1       1   
1    1211050782          1                1         0            1       1   
2    1307059817          0                0         0            1       1   
3     711007713          1                1         0            5       1   
4    1504073368          1                1         0            5       6   
..          ...        ...              ...       ...          ...     ...   
305  1307060199          1                1         1            5       3   
306  1412071562          0                0         1            4       3   
307  1108028108          1                1         1            3       3   
308   904013591          1                1         1            2       3   
309  1308060959          0                0         1            1       3   

     PerfScoreID  PayRate  Termd  PositionID  ...  DateofHire  \
0              3    28.50      0           1  ...  10-27-2008   
1              3    21.50      1           2  ...   2-16-2015   
2              3    16.56      0           2  ...  01-05-2015   
3              3    20.50      1           2  ...   9-26-2011   
4              3    55.00      1           3  ...   8-15-2011   
..           ...      ...    ...         ...  ...         ...   
305            3    62.00      1          27  ...   3-30-2015   
306            3    58.20      1          30  ...   2-17-2014   
307            3    56.20      0          28  ...  10-11-2014   
308            3    53.80      0          28  ...   6-30-2016   
309            3    53.00      0          28  ...  10-11-2014   

    DateofTermination ManagerID                       RecruitmentSource  \
0                 NaN       1.0                      Diversity Job Fair   
1            04-15-15       1.0                  Pay Per Click - Google   
2                 NaN       1.0                      Website Banner Ads   
3            09-25-13       1.0                      Diversity Job Fair   
4          02-14-2008      17.0  Social Networks - Facebook Twitter etc   
..                ...       ...                                     ...   
305          06-16-16       4.0              Company Intranet - Partner   
306          02-19-16       4.0                         Vendor Referral   
307               NaN       7.0                       Employee Referral   
308               NaN       7.0                    On-campus Recruiting   
309               NaN       7.0                       Employee Referral   

    EngagementSurvey EmpSatisfaction SpecialProjectsCount  \
0               2.04               2                    6   
1               3.24               3                    4   
2               5.00               3                    5   
3               3.80               4                    4   
4               3.14               5                    0   
..               ...             ...                  ...   
305             4.96               3                    6   
306             2.94               5                    7   
307             4.46               5                    6   
308             3.27               4                    5   
309             5.00               3                    4   

     LastPerformanceReview_Date Age  YearsOfExperience  
0                     1/15/2019  33                 12  
1                           NaN  35                  5  
2                     1/15/2019  32                  5  
3                           NaN  33                  9  
4                           NaN  56                  9  
..                          ...  ..                ...  
305                         NaN  45                  5  
306                         NaN  56                  6  
307                  01-07-2019  34                  6  
308                   1/14/2019  37                  4  
309                  01-02-2019

In [605]:
drop_columns(hr_dataset, 'EmpID')

In [606]:
drop_columns(hr_dataset, 'DateofHire')

In [607]:
drop_columns(hr_dataset, 'DOB')

In [608]:
hr_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 310 entries, 0 to 309
Data columns (total 22 columns):
MarriedID                     310 non-null int64
MaritalStatusID               310 non-null int64
GenderID                      310 non-null int64
EmpStatusID                   310 non-null int64
DeptID                        310 non-null int64
PerfScoreID                   310 non-null int64
PayRate                       310 non-null float64
Termd                         310 non-null int64
PositionID                    310 non-null int64
State                         310 non-null object
CitizenDesc                   310 non-null object
HispanicLatino                310 non-null object
RaceDesc                      310 non-null object
DateofTermination             103 non-null object
ManagerID                     302 non-null float64
RecruitmentSource             310 non-null object
EngagementSurvey              310 non-null float64
EmpSatisfaction               310 non-null int64
S

In [611]:
hr_num_ds = hr_dataset[['Age','YearsOfExperience','PayRate','EngagementSurvey','EmpSatisfaction','SpecialProjectsCount']].values

In [616]:
hr_num_ds = pd.DataFrame(hr_num_ds)

In [617]:
hr_num_ds.head()

0     1      2     3    4    5
0  33.0  12.0  28.50  2.04  2.0  6.0
1  35.0   5.0  21.50  3.24  3.0  4.0
2  32.0   5.0  16.56  5.00  3.0  5.0
3  33.0   9.0  20.50  3.80  4.0  4.0
4  56.0   9.0  55.00  3.14  5.0  0.0

In [644]:
from sklearn import preprocessing 
  

""" MIN MAX SCALER """
  
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1)) 
  
# Scaled feature 
x_after_min_max_scaler = min_max_scaler.fit_transform(hr_num_ds) 
  
print ("\nAfter min max Scaling : \n", x_after_min_max_scaler) 
  
  
""" Standardisation """
  
Standardisation = preprocessing.StandardScaler() 
  
# Scaled feature 
x_after_Standardisation = Standardisation.fit_transform(hr_num_ds) 
  
print ("\nAfter Standardisation : \n", x_after_Standardisation) 


After min max Scaling : 
 [[0.12195122 0.81818182 0.21969697 0.25440806 0.25       0.75      ]
 [0.17073171 0.18181818 0.11363636 0.55667506 0.5        0.5       ]
 [0.09756098 0.18181818 0.03878788 1.         0.5        0.625     ]
 ...
 [0.14634146 0.27272727 0.63939394 0.86397985 1.         0.75      ]
 [0.2195122  0.09090909 0.6030303  0.56423174 0.75       0.625     ]
 [0.65853659 0.27272727 0.59090909 1.         0.5        0.5       ]]

After Standardisation : 
 [[-0.95308775  2.41219942 -0.18131687 -1.00278605 -2.0790602   2.03998721]
 [-0.72720304 -1.20526619 -0.63708215 -0.07147558 -0.97921607  1.18827538]
 [-1.0660301  -1.20526619 -0.95872222  1.29444645 -0.97921607  1.6141313 ]
 ...
 [-0.84014539 -0.68848539  1.62221145  0.87535674  1.2204722   2.03998721]
 [-0.50131833 -1.72204699  1.46594907 -0.04819281  0.12062807  1.6141313 ]
 [ 1.53164407 -0.68848539  1.41386161  1.29444645 -0.97921607  1.18827538]]


In [623]:
x_after_Standardisation = pd.DataFrame(x_after_Standardisation)
x_after_Standardisation


0         1         2         3         4         5
0   -0.953088  2.412199 -0.181317 -1.002786 -2.079060  2.039987
1   -0.727203 -1.205266 -0.637082 -0.071476 -0.979216  1.188275
2   -1.066030 -1.205266 -0.958722  1.294446 -0.979216  1.614131
3   -0.953088  0.861857 -0.702191  0.363136  0.120628  1.188275
4    1.644586  0.861857  1.544080 -0.149085  1.220472 -0.515148
..        ...       ...       ...       ...       ...       ...
305  0.402221 -1.205266  1.999846  1.263403 -0.979216  2.039987
306  1.644586 -0.688485  1.752430 -0.304303  1.220472  2.465843
307 -0.840145 -0.688485  1.622211  0.875357  1.220472  2.039987
308 -0.501318 -1.722047  1.465949 -0.048193  0.120628  1.614131
309  1.531644 -0.688485  1.413862  1.294446 -0.979216  1.188275

[310 rows x 6 columns]

In [624]:

x_after_min_max_scaler = pd.DataFrame(x_after_min_max_scaler)
x_after_min_max_scaler

0         1         2         3     4      5
0    0.121951  0.818182  0.219697  0.254408  0.25  0.750
1    0.170732  0.181818  0.113636  0.556675  0.50  0.500
2    0.097561  0.181818  0.038788  1.000000  0.50  0.625
3    0.121951  0.545455  0.098485  0.697733  0.75  0.500
4    0.682927  0.545455  0.621212  0.531486  1.00  0.000
..        ...       ...       ...       ...   ...    ...
305  0.414634  0.181818  0.727273  0.989924  0.50  0.750
306  0.682927  0.272727  0.669697  0.481108  1.00  0.875
307  0.146341  0.272727  0.639394  0.863980  1.00  0.750
308  0.219512  0.090909  0.603030  0.564232  0.75  0.625
309  0.658537  0.272727  0.590909  1.000000  0.50  0.500

[310 rows x 6 columns]